export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const SELECTED_COVER_BEGIN = "SELECTED_COVER_BEGIN";
export const SELECTED_COVER_SUCCESS = "SELECTED_COVER_SUCCESS";
export const SELECTED_COVER_ERROR = "SELECTED_COVER_ERROR";

export const SELECTED_COUNTRY = "SELECTED_COUNTRY";

export const PASSWORD_MATCH = "PASSWORD_MATCH";
